name: e2e
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  e2e:
    name: cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
        with:
          ref: main
          node-version: 12
      - name: Run Cypress 🌲
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_BASE_URL: https://next.egghead.io

      - name: Cypress tests ✅
        if: ${{ success() }}
        run: |

          curl --request POST \
          --url ${{ secrets.EGGHEAD_STATUS_WEBHOOK }} \
          --header 'content-type: application/json' \
          --data '{
            "text": "All systems operational ✅"
          }'

      - name: Cypress tests 🚨
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url ${{ secrets.EGGHEAD_STATUS_WEBHOOK }} \
          --header 'content-type: application/json' \
          --data '{
            "text": "🚨 Check logs: https://github.com/eggheadio/egghead-next/actions?query=workflow%3Ae2e"            
          }'
